---
title: "Data science for cognitive neuroscience and psychology (short summer course version) – brief course overview"
author: "Ina Bornkessel-Schlesewsky"
date: "January 2021"
output: pdf_document
fontsize: 12pt
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Welcome!

Thank you for registering for the *Data science for cognitive neuroscience and psychology* short course.
This document provides a brief overview of the course.
All other materials will be provided upon course commencement.
Should you have any questions, please don't hesitate to contact me.

I look forward to exploring some data science fundamentals with you!

-- [Ina Bornkessel-Schlesewsky](mailto:Ina.Bornkessel-Schlesewsky@unisa.edu.au)

## Important details

### Days and times:

* Wednesday, Jan 20th -- Wednesday, Jan 27th; 9:30 am -- 12:00 pm & 1:00 pm -- 4:00 pm on each day^[Note that each morning and afternoon session will include short breaks.]
* Note that the course will not take place on Tuesday, Jan 26th due to the Australia Day public holiday

Room: MAG B1-52

### What you will need:

Please bring a laptop with which you can access the internet to each session (and a charger if needed).

### Preparation:

You do not need to do anything to prepare for this course, as it is designed to be self-contained.
Parts of the course will be loosely based on the book *R for Data Science* by Hadley Wickham and Garrett Grolemund.
If you want to check it out before the course, it is freely available [here](https://r4ds.had.co.nz/).

### Join the course workspace on Slack:

We will be using [Slack](https://slack.com/intl/en-au/) for communications about the course, e.g. for announcements, questions etc. You can join the course workspace via the following link:

https://join.slack.com/t/unisa-wg54095/shared_invite/zt-kqmur62d-hspieJMUbw7QD1B6VkmH_A


## Brief course overview

The following units are designed to roughly correspond to one day each, but this might not be a one-to-one mapping. We will see how we go!

### Unit 1: Introduction and basics
* Introduction: What is data science and why do we need it? More specifically, why do psychologists and cognitive neuroscientists need it?
* What to expect in this course
* Basic concepts of data exploration and visualisation
* Basic introduction to R and RStudio Cloud (the platform which we will be using for most of this course)
* Reproducible research and reproducible reports

### Unit 2: Data wrangling and more on R
* Getting to know R — let’s dig a big deeper
* Data wrangling: getting data into the right shape for exploration / visualisation
* More on exploration and visualisation using other examples
* Tips on what to look for and what to avoid

### Unit 3: Open science
* Introduction to open science
* More on reproducibility and how RMarkdown can help
* Sharing and collaboration: introducing repositories and version control (e.g. git and GitHub; OSF)
* Others tools to foster open science (e.g. preprints and registered reports)

### Unit 4: Your own project!
* Putting it all together with a mini project of your own choosing
* Work through from scratch to produce a reproducible report

### Unit 5: Next steps
* Getting yourself set up for your own projects -- installing R, RStudio, git etc. on your own computer
* Workflow tips
* Working as a team
* Where to go from here